# Site settings
title: bayern-sightsleeping
client:
  name: Sightsleeping® in Bayern
  link: ""
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Abu Dhabi - Eine moderne Oase am Arabischen Golf, eingerahmt von spektakulären Mangrovenlandschaften, majestätischen Wüsten und exotischen Bilderbuchstränden – wie geschaffen für eine märchenhaft orientalische Auszeit voll futuristischer Highlights und architektonischer Superlative. Erleben Sie eine dynamische Metropole, in der Träume glamouröse Wirklichkeit werden bei einem kultivierten Citytrip oder einem exklusiven Strandurlaub zwischen Dünen und Mangroven.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/bayern-sightsleeping" # the subpath of your site, e.g. /blog/
img:     "/de/bayern-sightsleeping/_assets/img"
css:     "/de/bayern-sightsleeping/_assets/css"
js:      "/de/bayern-sightsleeping/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
