# Site settings
title: Sightsleeping® in Bayern
client:
  name: Sightsleeping® in Bayern
  link: "https://www.bavaria.by/"
core-se-link: https://www.secretescapes.de/aktuelle-angebote
description: >
  Die Marke Sightsleeping® führt Sie zu den kulturellen und historischen Highlights Bayerns und lädt Sie ein, in ausgewählten Unterkünften und an einzigartigen Orten zu residieren.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/de/bayern-sightsleeping" # the subpath of your site, e.g. /blog/
img:     "/de/bayern-sightsleeping/_assets/img"
css:     "/de/bayern-sightsleeping/_assets/css"
js:      "/de/bayern-sightsleeping/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed
